server:
  port: 8082
  servlet:
    context-path: /cmfz
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
  mvc:
    view:
      suffix: .jsp
      prefix: /
    date-format: yyyy-MM-dd
    jackson:
      date-format: yyyy-MM-dd
  http:
    encoding:
      force-request: true
      charset: UTF-8
      force-response: true
      force: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*